# Generated by Django 5.1.15 on 2026-02-27 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrescriptionForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "predicted_count",
                    models.PositiveIntegerField(verbose_name="予測枚数"),
                ),
                (
                    "lower_bound",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="信頼区間下限"
                    ),
                ),
                (
                    "upper_bound",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="信頼区間上限"
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="モデルバージョン",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription_forecasts",
                        to="stores.store",
                        verbose_name="店舗",
                    ),
                ),
            ],
            options={
                "verbose_name": "処方予測",
                "verbose_name_plural": "処方予測",
                "db_table": "prescription_forecasts",
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("store", "date"), name="unique_store_date_forecast"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                ("count", models.PositiveIntegerField(verbose_name="処方枚数")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("scraping", "スクレイピング"),
                            ("csv_upload", "CSVアップロード"),
                        ],
                        default="scraping",
                        max_length=20,
                        verbose_name="データソース",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription_records",
                        to="stores.store",
                        verbose_name="店舗",
                    ),
                ),
            ],
            options={
                "verbose_name": "処方実績",
                "verbose_name_plural": "処方実績",
                "db_table": "prescription_records",
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("store", "date"), name="unique_store_date_prescription"
                    )
                ],
            },
        ),
    ]
