# Generated by Django 5.1.15 on 2026-02-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfluenzaReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="年")),
                ("week", models.PositiveIntegerField(verbose_name="週番号")),
                (
                    "prefecture",
                    models.CharField(max_length=10, verbose_name="都道府県"),
                ),
                (
                    "disease",
                    models.CharField(
                        default="インフルエンザ", max_length=100, verbose_name="疾病名"
                    ),
                ),
                (
                    "patients",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="定点当たり報告数",
                    ),
                ),
                (
                    "total_reports",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="総報告数"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "感染症定点報告",
                "verbose_name_plural": "感染症定点報告",
                "db_table": "influenza_reports",
                "ordering": ["-year", "-week"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "week", "prefecture", "disease"),
                        name="unique_influenza_report",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeatherRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "station_name",
                    models.CharField(max_length=50, verbose_name="観測所名"),
                ),
                (
                    "station_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="観測所コード",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "avg_temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="日平均気温(℃)",
                    ),
                ),
                (
                    "max_temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="日最高気温(℃)",
                    ),
                ),
                (
                    "min_temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="日最低気温(℃)",
                    ),
                ),
                (
                    "precipitation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=7,
                        null=True,
                        verbose_name="降水量(mm)",
                    ),
                ),
                (
                    "humidity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="平均湿度(%)",
                    ),
                ),
                (
                    "snowfall",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=7,
                        null=True,
                        verbose_name="降雪量(cm)",
                    ),
                ),
                (
                    "snow_depth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=7,
                        null=True,
                        verbose_name="積雪深(cm)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "気象データ",
                "verbose_name_plural": "気象データ",
                "db_table": "weather_records",
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("station_name", "date"),
                        name="unique_weather_station_date",
                    )
                ],
            },
        ),
    ]
