# Generated by Django 5.1.15 on 2026-02-27 12:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shifts", "0001_initial"),
        ("staff", "0001_initial"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "P1: 緊急欠員・法的違反回避"),
                            (2, "P2: 義務有給5日消化"),
                            (3, "P3: 薬局長・管理薬剤師の公休確保"),
                            (4, "P4: 希望休・健康診断"),
                            (5, "P5: その他有給・任意休暇"),
                        ],
                        default=5,
                        verbose_name="優先度",
                    ),
                ),
                (
                    "base_difficulty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="基本難易度",
                    ),
                ),
                (
                    "attending_pharmacists",
                    models.PositiveIntegerField(default=0, verbose_name="同勤薬剤師数"),
                ),
                (
                    "attending_clerks",
                    models.PositiveIntegerField(default=0, verbose_name="同勤事務員数"),
                ),
                (
                    "has_chief_present",
                    models.BooleanField(default=False, verbose_name="薬局長出勤"),
                ),
                (
                    "solo_hours",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        max_digits=4,
                        verbose_name="一人薬剤師対応時間",
                    ),
                ),
                (
                    "prescription_forecast",
                    models.CharField(
                        choices=[
                            ("A", "A（多）"),
                            ("B", "B（やや多）"),
                            ("C", "C（普通）"),
                            ("D", "D（やや少）"),
                            ("E", "E（少）"),
                        ],
                        default="C",
                        max_length=1,
                        verbose_name="処方予測",
                    ),
                ),
                (
                    "effective_difficulty_hr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="実効難易度（HR単位）",
                    ),
                ),
                (
                    "required_hr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="必要HR値",
                    ),
                ),
                (
                    "is_filled",
                    models.BooleanField(default=False, verbose_name="充足済み"),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="備考")),
                (
                    "shift_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_slots",
                        to="shifts.shiftperiod",
                        verbose_name="シフト期間",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_slots",
                        to="stores.store",
                        verbose_name="店舗",
                    ),
                ),
            ],
            options={
                "verbose_name": "応援枠",
                "verbose_name_plural": "応援枠",
                "db_table": "support_slots",
                "ordering": ["priority", "date"],
            },
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("candidate", "候補"),
                            ("confirmed", "確定"),
                            ("rejected", "却下"),
                        ],
                        default="candidate",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="承認日時"
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        verbose_name="スコア",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_assignments",
                        to="staff.staff",
                        verbose_name="承認者",
                    ),
                ),
                (
                    "rounder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="staff.rounder",
                        verbose_name="ラウンダー",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="assignments.supportslot",
                        verbose_name="応援枠",
                    ),
                ),
            ],
            options={
                "verbose_name": "アサイン",
                "verbose_name_plural": "アサイン",
                "db_table": "assignments",
                "ordering": ["-score"],
            },
        ),
    ]
