# Generated by Django 4.2.28 on 2026-02-28 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('staff', '0002_staff_monthly_working_days'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('candidate', '候補'), ('confirmed', '確定'), ('rejected', '却下'), ('cancelled', '取消'), ('handed_over', '引継ぎ')], default='candidate', max_length=20, verbose_name='ステータス'),
        ),
        migrations.CreateModel(
            name='AssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=20, verbose_name='変更前ステータス')),
                ('to_status', models.CharField(max_length=20, verbose_name='変更後ステータス')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='通知送信済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='assignments.assignment', verbose_name='アサイン')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_log_actions', to='staff.staff', verbose_name='操作者')),
                ('notification_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_logs', to='notifications.notificationlog', verbose_name='通知ログ')),
            ],
            options={
                'verbose_name': 'アサイン証跡',
                'verbose_name_plural': 'アサイン証跡',
                'db_table': 'assignment_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
