# Generated by Django 5.1.15 on 2026-02-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("shift_confirmed", "シフト確定"),
                            ("assignment_generated", "応援アサイン案生成"),
                            ("leave_deadline_soon", "希望休締め切り3日前"),
                            ("paid_leave_warning", "有休消化期限30日前"),
                            ("paid_leave_urgent", "有休消化期限7日前"),
                            ("paid_leave_overdue", "義務有給期限超過"),
                            ("unfilled_slot_alert", "充足不可アラート"),
                            ("evaluation_bias", "不正評価検知"),
                        ],
                        max_length=50,
                        verbose_name="トリガー",
                    ),
                ),
                (
                    "recipient_zoom_account",
                    models.EmailField(
                        max_length=254, verbose_name="送信先Zoomアカウント"
                    ),
                ),
                ("message", models.TextField(verbose_name="通知内容")),
                (
                    "is_sent",
                    models.BooleanField(default=False, verbose_name="送信済み"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="エラー詳細"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "通知ログ",
                "verbose_name_plural": "通知ログ",
                "db_table": "notification_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
