# Generated by Django 5.1.15 on 2026-02-27 12:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HrEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="評価期間開始")),
                ("period_end", models.DateField(verbose_name="評価期間終了")),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-1.0")),
                            django.core.validators.MaxValueValidator(Decimal("1.0")),
                        ],
                        verbose_name="評価スコア",
                    ),
                ),
                (
                    "evaluation_type",
                    models.CharField(
                        choices=[("supervisor", "応援担当評価"), ("self", "自己評価")],
                        default="supervisor",
                        max_length=20,
                        verbose_name="評価種別",
                    ),
                ),
                ("reason", models.TextField(verbose_name="評価理由")),
                (
                    "rounder_comment",
                    models.TextField(
                        blank=True, default="", verbose_name="本人異議コメント"
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False,
                        help_text="同一評価者から2クール連続-1の場合にTrue",
                        verbose_name="上位承認必要",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="given_evaluations",
                        to="staff.staff",
                        verbose_name="評価者",
                    ),
                ),
                (
                    "rounder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluations",
                        to="staff.rounder",
                        verbose_name="被評価者",
                    ),
                ),
            ],
            options={
                "verbose_name": "HR評価",
                "verbose_name_plural": "HR評価",
                "db_table": "hr_evaluations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HrPeriodSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="期間開始")),
                ("period_end", models.DateField(verbose_name="期間終了")),
                (
                    "supervisor_total",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        max_digits=5,
                        verbose_name="応援担当評価合計",
                    ),
                ),
                (
                    "self_total",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        max_digits=5,
                        verbose_name="自己評価合計",
                    ),
                ),
                (
                    "carried_over",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        max_digits=5,
                        verbose_name="前期繰越ポイント",
                    ),
                ),
                (
                    "total_points",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        max_digits=6,
                        verbose_name="累積ポイント",
                    ),
                ),
                (
                    "computed_hr",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("20"),
                        max_digits=5,
                        verbose_name="算出HR値",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "rounder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hr_summaries",
                        to="staff.rounder",
                        verbose_name="ラウンダー",
                    ),
                ),
            ],
            options={
                "verbose_name": "HR期間サマリー",
                "verbose_name_plural": "HR期間サマリー",
                "db_table": "hr_period_summaries",
                "ordering": ["-period_start"],
                "unique_together": {("rounder", "period_start")},
            },
        ),
    ]
