# Generated by Django 5.1.15 on 2026-02-27 12:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="氏名")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("pharmacist", "薬剤師"),
                            ("clerk", "事務員"),
                            ("managing_pharmacist", "管理薬剤師"),
                        ],
                        max_length=30,
                        verbose_name="職種",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "正社員"),
                            ("part_time", "パート"),
                            ("dispatch", "派遣"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="雇用形態",
                    ),
                ),
                (
                    "is_rounder",
                    models.BooleanField(default=False, verbose_name="ラウンダー"),
                ),
                (
                    "paid_leave_deadline",
                    models.CharField(
                        choices=[("09/15", "9月15日"), ("02/15", "2月15日")],
                        default="09/15",
                        max_length=5,
                        verbose_name="義務有給期限区分",
                    ),
                ),
                (
                    "paid_leave_used",
                    models.PositiveIntegerField(default=0, verbose_name="当期消化日数"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_members",
                        to="stores.store",
                        verbose_name="所属店舗",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザーアカウント",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタッフ",
                "verbose_name_plural": "スタッフ",
                "db_table": "staff",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Rounder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hunter_rank",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("20.0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="HR値",
                    ),
                ),
                (
                    "can_work_alone",
                    models.BooleanField(default=False, verbose_name="一人薬剤師対応可"),
                ),
                (
                    "max_prescriptions",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[django.core.validators.MaxValueValidator(50)],
                        verbose_name="1日対応上限枚数",
                    ),
                ),
                (
                    "has_car",
                    models.BooleanField(default=False, verbose_name="自家用車有無"),
                ),
                (
                    "can_long_distance",
                    models.BooleanField(default=False, verbose_name="長距離移動可"),
                ),
                (
                    "managing_pharmacist_years",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        max_digits=4,
                        verbose_name="管理薬剤師経験年数",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounder_profile",
                        to="staff.staff",
                        verbose_name="スタッフ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ラウンダー",
                "verbose_name_plural": "ラウンダー",
                "db_table": "rounders",
            },
        ),
        migrations.CreateModel(
            name="RounderStoreExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_visit_date",
                    models.DateField(blank=True, null=True, verbose_name="初回入店日"),
                ),
                (
                    "last_visit_date",
                    models.DateField(blank=True, null=True, verbose_name="最終入店日"),
                ),
                (
                    "visit_count",
                    models.PositiveIntegerField(default=1, verbose_name="入店回数"),
                ),
                (
                    "rounder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_experiences",
                        to="staff.rounder",
                        verbose_name="ラウンダー",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experienced_rounders",
                        to="stores.store",
                        verbose_name="店舗",
                    ),
                ),
            ],
            options={
                "verbose_name": "ラウンダー経験店舗",
                "verbose_name_plural": "ラウンダー経験店舗",
                "db_table": "rounder_store_experience",
                "unique_together": {("rounder", "store")},
            },
        ),
    ]
