# Generated by Django 5.1.15 on 2026-02-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='monthly_working_days',
            field=models.PositiveIntegerField(blank=True, help_text='シフト期間あたりの所定労働日数（未設定時は雇用形態から自動算出）', null=True, verbose_name='月間所定労働日数'),
        ),
    ]
