# Generated by Django 4.2.28 on 2026-02-28 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
        ('staff', '0002_staff_monthly_working_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='RounderUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='', verbose_name='理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('rounder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='staff.rounder', verbose_name='ラウンダー')),
                ('shift_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounder_unavailabilities', to='shifts.shiftperiod', verbose_name='応援不可期間')),
            ],
            options={
                'verbose_name': 'ラウンダー応援不可期間',
                'verbose_name_plural': 'ラウンダー応援不可期間',
                'db_table': 'rounder_unavailabilities',
                'unique_together': {('rounder', 'shift_period')},
            },
        ),
    ]
