# Generated by Django 4.2.28 on 2026-02-28 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0002_store_min_pharmacists'),
        ('staff', '0003_rounderunavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='', verbose_name='理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('from_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='stores.store', verbose_name='異動元店舗')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='staff.staff', verbose_name='スタッフ')),
                ('to_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='stores.store', verbose_name='異動先店舗')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_transfers', to=settings.AUTH_USER_MODEL, verbose_name='実行者')),
            ],
            options={
                'verbose_name': '異動履歴',
                'verbose_name_plural': '異動履歴',
                'db_table': 'staff_transfers',
                'ordering': ['-created_at'],
            },
        ),
    ]
