# Generated by Django 4.2.28 on 2026-03-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_stafftransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='work_status',
            field=models.CharField(choices=[('active', '通常勤務'), ('on_leave', '休職中'), ('maternity', '産休・育休中'), ('temporary', '臨時人員')], default='active', max_length=20, verbose_name='稼働状況'),
        ),
    ]
