# Generated by Django 5.1.15 on 2026-02-27 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staff", "0001_initial"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="開始日")),
                ("end_date", models.DateField(verbose_name="終了日")),
                (
                    "request_deadline",
                    models.DateField(
                        help_text="シフト開始15日前", verbose_name="希望休申請締め切り"
                    ),
                ),
                (
                    "is_finalized",
                    models.BooleanField(default=False, verbose_name="確定済み"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "シフト期間",
                "verbose_name_plural": "シフト期間",
                "db_table": "shift_periods",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "shift_type",
                    models.CharField(
                        choices=[
                            ("full", "全日"),
                            ("morning", "午前"),
                            ("afternoon", "午後"),
                        ],
                        default="full",
                        max_length=10,
                        verbose_name="シフト種別",
                    ),
                ),
                (
                    "leave_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("paid", "有給"),
                            ("holiday", "公休"),
                            ("sick", "病欠"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="休暇種別",
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(default=False, verbose_name="確定済み"),
                ),
                (
                    "is_late_request",
                    models.BooleanField(default=False, verbose_name="遅延申請"),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="staff.staff",
                        verbose_name="スタッフ",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shifts",
                        to="stores.store",
                        verbose_name="出勤店舗",
                    ),
                ),
                (
                    "shift_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="shifts.shiftperiod",
                        verbose_name="シフト期間",
                    ),
                ),
            ],
            options={
                "verbose_name": "シフト",
                "verbose_name_plural": "シフト",
                "db_table": "shifts",
                "ordering": ["date", "staff"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("staff", "date", "shift_type"),
                        name="unique_staff_date_shift_type",
                    )
                ],
            },
        ),
    ]
