# Generated by Django 5.1.15 on 2026-02-27 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="休暇日")),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("paid", "有給"),
                            ("holiday", "公休"),
                            ("sick", "病欠"),
                            ("other", "その他"),
                        ],
                        max_length=20,
                        verbose_name="休暇種別",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, default="", verbose_name="申請理由"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "申請中"),
                            ("approved", "承認"),
                            ("rejected", "却下"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "review_comment",
                    models.TextField(
                        blank=True, default="", verbose_name="承認/却下コメント"
                    ),
                ),
                (
                    "is_late",
                    models.BooleanField(
                        default=False,
                        help_text="シフト希望休申請締め切り後の申請",
                        verbose_name="締め切り後申請",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申請日時"),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_leave_requests",
                        to="staff.staff",
                        verbose_name="承認者",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="staff.staff",
                        verbose_name="スタッフ",
                    ),
                ),
            ],
            options={
                "verbose_name": "休暇申請",
                "verbose_name_plural": "休暇申請",
                "db_table": "leave_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
