# Generated by Django 5.1.15 on 2026-02-27 12:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="店舗名")),
                (
                    "area",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="エリア区分"
                    ),
                ),
                (
                    "base_difficulty",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("3.0"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1.0")),
                            django.core.validators.MaxValueValidator(Decimal("5.0")),
                        ],
                        verbose_name="基本難易度",
                    ),
                ),
                (
                    "slots",
                    models.PositiveIntegerField(default=1, verbose_name="応援枠数"),
                ),
                (
                    "has_controlled_medical_device",
                    models.BooleanField(default=False, verbose_name="高度管理医療機器"),
                ),
                (
                    "has_toxic_substances",
                    models.BooleanField(default=False, verbose_name="毒劇物販売"),
                ),
                (
                    "has_workers_comp",
                    models.BooleanField(default=False, verbose_name="労災対応"),
                ),
                (
                    "has_auto_insurance",
                    models.BooleanField(default=False, verbose_name="自賠責対応"),
                ),
                (
                    "has_special_public_expense",
                    models.BooleanField(default=False, verbose_name="特殊公費"),
                ),
                (
                    "has_local_voucher",
                    models.BooleanField(default=False, verbose_name="地方振興券対応"),
                ),
                (
                    "has_holiday_rules",
                    models.BooleanField(
                        default=False, verbose_name="祝日出勤特殊ルール"
                    ),
                ),
                (
                    "zoom_account",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Zoomアカウント",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "店舗",
                "verbose_name_plural": "店舗",
                "db_table": "stores",
                "ordering": ["name"],
            },
        ),
    ]
