# Generated by Django 5.1.15 on 2026-02-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='min_pharmacists',
            field=models.PositiveIntegerField(default=1, help_text='1日に必要な最低薬剤師数（平日基準）', verbose_name='必要最低薬剤師数'),
        ),
    ]
