# Generated by Django 4.2.28 on 2026-03-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_min_pharmacists'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='operates_on_holidays',
            field=models.BooleanField(default=False, help_text='True の場合、祝日も通常営業として扱う', verbose_name='祝日営業'),
        ),
    ]
