# Generated by Django 4.2.28 on 2026-03-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_operates_on_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='monthly_working_days',
            field=models.PositiveIntegerField(blank=True, help_text='シフト期間あたりの所定労働日数（未設定時はスタッフの雇用形態から自動算出）', null=True, verbose_name='月間所定労働日数'),
        ),
    ]
