# Generated by Django 4.2.28 on 2026-02-28 20:16

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0002_store_min_pharmacists'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffingAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('delta', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('-5.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='調整値')),
                ('source', models.CharField(choices=[('manual', '手動'), ('model', 'モデル予測')], default='manual', max_length=10, verbose_name='ソース')),
                ('note', models.TextField(blank=True, default='', verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('shift_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffing_adjustments', to='shifts.shiftperiod', verbose_name='シフト期間')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffing_adjustments', to='stores.store', verbose_name='店舗')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '人工調整',
                'verbose_name_plural': '人工調整',
                'db_table': 'staffing_adjustments',
                'ordering': ['store', 'date'],
            },
        ),
        migrations.AddConstraint(
            model_name='staffingadjustment',
            constraint=models.UniqueConstraint(fields=('store', 'shift_period', 'date'), name='unique_store_period_date'),
        ),
    ]
