# Generated by Django 4.2.28 on 2026-03-01 00:47

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_min_pharmacists'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staffing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreWeekdayAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, '月曜'), (1, '火曜'), (2, '水曜'), (3, '木曜'), (4, '金曜'), (5, '土曜'), (6, '日曜')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='曜日')),
                ('delta', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('-5.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='調整値')),
                ('note', models.TextField(blank=True, default='', verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekday_adjustments', to='stores.store', verbose_name='店舗')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '曜日別調整',
                'verbose_name_plural': '曜日別調整',
                'db_table': 'store_weekday_adjustments',
                'ordering': ['store', 'day_of_week'],
            },
        ),
        migrations.AddConstraint(
            model_name='storeweekdayadjustment',
            constraint=models.UniqueConstraint(fields=('store', 'day_of_week'), name='unique_store_day_of_week'),
        ),
    ]
