# Generated by Django 4.2.28 on 2026-03-01 02:10

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0003_store_operates_on_holidays'),
        ('staffing', '0002_storeweekdayadjustment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyScheduleOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('is_open', models.BooleanField(help_text='True=臨時営業, False=臨時休業', verbose_name='営業')),
                ('note', models.TextField(blank=True, default='', verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_overrides', to='stores.store', verbose_name='店舗')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '日次営業オーバーライド',
                'verbose_name_plural': '日次営業オーバーライド',
                'db_table': 'daily_schedule_overrides',
                'ordering': ['store', 'date'],
            },
        ),
        migrations.CreateModel(
            name='StoreWeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, '月曜'), (1, '火曜'), (2, '水曜'), (3, '木曜'), (4, '金曜'), (5, '土曜'), (6, '日曜')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='曜日')),
                ('is_open', models.BooleanField(default=True, verbose_name='営業')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='開店時間')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='閉店時間')),
                ('staffing_delta', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('-5.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))], verbose_name='人工調整')),
                ('note', models.TextField(blank=True, default='', verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='stores.store', verbose_name='店舗')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': '曜日別営業設定',
                'verbose_name_plural': '曜日別営業設定',
                'db_table': 'store_weekly_schedules',
                'ordering': ['store', 'day_of_week'],
            },
        ),
        migrations.DeleteModel(
            name='StoreWeekdayAdjustment',
        ),
        migrations.AddConstraint(
            model_name='storeweeklyschedule',
            constraint=models.UniqueConstraint(fields=('store', 'day_of_week'), name='unique_store_day_of_week'),
        ),
        migrations.AddConstraint(
            model_name='dailyscheduleoverride',
            constraint=models.UniqueConstraint(fields=('store', 'date'), name='unique_store_date_override'),
        ),
    ]
