# Generated by Django 4.2.28 on 2026-03-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0003_dailyscheduleoverride_storeweeklyschedule_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staffingadjustment',
            name='unique_store_period_date',
        ),
        migrations.AddConstraint(
            model_name='staffingadjustment',
            constraint=models.UniqueConstraint(fields=('store', 'shift_period', 'date', 'source'), name='unique_store_period_date_source'),
        ),
    ]
